apiVersion: apps/v1
kind: Deployment
metadata:
  name: onfinance
  labels:
    app: onfinance
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onfinance
  template:
    metadata:
      labels:
        app: onfinance
    spec:
      containers:
      - name: onfinance
        image: onfinance:2.0
        ports:
        - containerPort: 8000